CREATE TABLE RESERVATIONS 
(
  RES_ID NUMBER(6) NOT NULL 
, RES_ROOM_NUMBER NUMBER(6) NOT NULL 
, RES_CLIENT_ID NUMBER(6) NOT NULL 
, RES_ARRIVAL_DATE DATE NOT NULL 
, RES_DEPARTURE_DATE DATE NOT NULL 
, CONSTRAINT RESERVATIONS_PK PRIMARY KEY 
  (
    RES_ID 
  )
  ENABLE 
);

ALTER TABLE RESERVATIONS
ADD CONSTRAINT RESERVATIONS_FK1 FOREIGN KEY
(
  RES_ROOM_NUMBER 
)
REFERENCES ROOMS
(
  ROOM_NUMBER 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE RESERVATIONS
ADD CONSTRAINT RESERVATIONS_FK2 FOREIGN KEY
(
  RES_CLIENT_ID 
)
REFERENCES CLIENTS
(
  CLIENT_ID 
)
ON DELETE CASCADE ENABLE;

