CREATE TABLE CLIENTS 
(
  CLIENT_ID NUMBER(6) NOT NULL 
, C_PASSPORT VARCHAR2(20) NOT NULL 
, C_SURNAME VARCHAR2(40) NOT NULL 
, C_NAME VARCHAR2(40) NOT NULL 
, C_PATRONYMIC VARCHAR2(40) 
, C_ADDRESS VARCHAR2(60) NOT NULL 
, C_PHONE VARCHAR2(20) 
, C_DISCOUNT NUMBER DEFAULT 0 NOT NULL 
, C_COMMENT VARCHAR2(150) 
, CONSTRAINT CLIENTS_PK PRIMARY KEY 
  (
    CLIENT_ID 
  )
  ENABLE 
);

