CREATE TABLE ACCOMMODATIONS 
(
  ACCOM_ID NUMBER(6) NOT NULL 
, ACCOM_ROOM_NUMBER NUMBER(6) NOT NULL 
, ACCOM_CLIENT_ID NUMBER(6) NOT NULL 
, ACCOM_ARRIVAL_DATE DATE NOT NULL 
, ACCOM_DEPARTURE_DATE DATE NOT NULL 
, CONSTRAINT ACCOMMODATIONS_PK PRIMARY KEY 
  (
    ACCOM_ID 
  )
  ENABLE 
);

ALTER TABLE ACCOMMODATIONS
ADD CONSTRAINT ACCOMMODATIONS_FK1 FOREIGN KEY
(
  ACCOM_ROOM_NUMBER 
)
REFERENCES ROOMS
(
  ROOM_NUMBER 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE ACCOMMODATIONS
ADD CONSTRAINT ACCOMMODATIONS_FK2 FOREIGN KEY
(
  ACCOM_CLIENT_ID 
)
REFERENCES CLIENTS
(
  CLIENT_ID 
)
ON DELETE CASCADE ENABLE;

