CREATE TABLE ROOMS 
(
  ROOM_NUMBER NUMBER(3) NOT NULL 
, R_COUNT NUMBER(2) DEFAULT 0 NOT NULL 
, R_PRICE NUMBER(7, 2) DEFAULT 0.00 NOT NULL 
, R_COMFORT VARCHAR2(20) NOT NULL 
, CONSTRAINT ROOMS_PK PRIMARY KEY 
  (
    ROOM_NUMBER 
  )
  ENABLE 
);

ALTER TABLE ROOMS
ADD CONSTRAINT ROOMS_CHK1 CHECK 
(R_COMFORT = 'studio' or R_COMFORT = 'luxe' or
 R_COMFORT = 'apartment' or R_COMFORT = 'suite')
ENABLE;

