-- USER SQL
CREATE USER Hotel IDENTIFIED BY 1 
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS

-- ROLES
GRANT "CONNECT" TO Hotel ;
GRANT "RESOURCE" TO Hotel ;

-- SYSTEM PRIVILEGES
GRANT CREATE ROLE TO Hotel ;
GRANT CREATE TRIGGER TO Hotel ;
GRANT CREATE MATERIALIZED VIEW TO Hotel ;
GRANT CREATE VIEW TO Hotel ;
GRANT CREATE TYPE TO Hotel ;
GRANT CREATE PUBLIC SYNONYM TO Hotel ;
GRANT CREATE SYNONYM TO Hotel ;
GRANT CREATE SEQUENCE TO Hotel ;
GRANT CREATE DATABASE LINK TO Hotel ;
GRANT CREATE PROCEDURE TO Hotel ;
