CREATE TABLE DECEMBER
(
  D_ACCOM_ID NUMBER(6) NOT NULL 
, D_ACCOM_ROOM_NUMBER NUMBER(6) NOT NULL 
, D_ACCOM_CLIENT_ID NUMBER(6) NOT NULL 
, D_ACCOM_ARRIVAL_DATE DATE NOT NULL 
, D_ACCOM_DEPARTURE_DATE DATE NOT NULL 
, CONSTRAINT DECEMBER_PK PRIMARY KEY 
  (
    D_ACCOM_ID 
  )
  ENABLE 
);

